### ISSUE TITLE
数据格式建议去掉rules层

### ISSUE THREAD

**Issue by ousinka** [D-xuanmo/v-form#17]
最新版本已经由原来Map格式改为了数据格式，进一步方便后端api接口配置。
建议再去掉rules层，进一步简便后端接口处理。
如下格式：
{
          key: 'text1',
          value: '',
          label: '关联文字1',
          type: 'VInput',
          vRules: 'required',
          placeholder: '请输入关联文字1',
          errorMsg: '请输入关联文字1',
          extra: 'extra'
        }

**Comment by D-xuanmo** [comment]
[参考commit](https://github.com/D-xuanmo/v-form/commit/97064e6b8e22819664bf0662fc936f8a485e247e)
