### ISSUE TITLE
正则校验时，建议考虑必填和非必填两种场景

### ISSUE THREAD

**Issue by ousinka** [D-xuanmo/v-form#23]
在正则校验时，是否可以参考自定义方法格式，将vRules: /\d+/ 改为 vRules: "required|/\d+/"。
同时满足两种场景：1、必填，也要满足一定格式要求。2，非必填，填写后要满足一定要求。

**Comment by D-xuanmo** [comment]
正则校验改为 `pattern` 字段，校验顺序为：required => pattern => vRules 剩余规则
