### ISSUE TITLE
测试了一下，整体都挺好的。唯一有个麻烦的地方就是每个cell的配置项文档不太清晰

### ISSUE THREAD

**Issue by LDXu** [D-xuanmo/v-form#42]
看到了表单的属性都全的，但是每个组件的属性配置没有。
每个cell的配置项文档需要看demo或者查看源代码。
readme.md的每个组件下能否补全一下属性名以及该属性的默认值。
类似：https://vant-contrib.gitee.io/vant/#/zh-CN/calendar#props

**Comment by LDXu** [comment]
每个组件内部实现都写了一遍，能否每个组件有几个固定的属性，然后其他属性都可以使用attrs，直接参考有赞的每个组件的属性。(attrs平时用得不多)

**Comment by D-xuanmo** [comment]
@LDXu  
- 目前文档确实不是很详细，需要看一下源码，最近有计划完善一下文档说明，也会加入新功能；
- 固定属性这个可以考虑实现一下，之前的版本在这一块并没有做太多的优化。

**Comment by LDXu** [comment]
好的，多谢，期待你的更新
