### ISSUE TITLE
请教个问题，mixins里面的e__change方法是不是没有用到

### ISSUE THREAD

**Issue by LDXu** [D-xuanmo/v-form#47]
看了下源码，有个小疑问。
 e__change(value) {
      this.$emit('change', {
        ...this.formModel,
        value
      })
    },

demo里面的change也是debounceChange触发的
校验都是watch value来触发检测的。
是不是e__change方法是不是没有用到？

**Comment by LDXu** [comment]
应该是V这层的组件的@change事件

**Comment by D-xuanmo** [comment]
@LDXu `e__change` 目前是各控件像 `VForm` 组件传递数据使用的，`debounceChange` 是用于传递组件数据到调用的地方，`e__change` 可以理解为内部组件使用
