### ISSUE TITLE
 Unknown custom element: <v-form> - did you register the component correctly? 

### ISSUE THREAD

**Issue by bigdong89** [D-xuanmo/v-form#5]
[Vue warn]: Unknown custom element: <v-form> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

版本v1.1.4  vant-ui 按需安装
导入方式采用:
import VForm from "@xuanmo/v-form/dist/v-form.umd.js";
import "@xuanmo/v-form/dist/v-form.css";
Vue.use(VForm)

node: 8.0 vue: 2
导出来的VForm打印出来是：
install: ƒ install(vue)
arguments: (...)
caller: (...)
length: 1
name: "install"
prototype: {constructor: ƒ}
__proto__: ƒ ()
[[FunctionLocation]]: v-form.umd.js?9ff8:17672
[[Scopes]]: Scopes[4]

似乎也没有问题，但是为啥总是显示没有注册呢？

**Comment by D-xuanmo** [comment]
@bigdong89 你是具体怎么使用报错的呢？可以使用这个平台重现一下：[https://codesandbox.io/](https://codesandbox.io/)

**Comment by bigdong89** [comment]
找到原因了，vue version要提升到^2.6.11 而且对应的vue-template-compiler也要对应^2.6.11
谢谢！您在上海吗？我在北京

**Comment by D-xuanmo** [comment]
@bigdong89 解决就好，是的，我在上海
