### ISSUE TITLE
vite+vue2.7 安装报错

### ISSUE THREAD

**Issue by snoopy1412** [D-xuanmo/v-form#62]
Uncaught SyntaxError: The requested module '/node_modules/@xuanmo/javascript-utils/dist/javascript-utils.esm.min.js?v=2df75d90' does not provide an export named 'countdown' (at verificationCode.vue:26:1)

**Comment by mynameshowlo** [comment]
javascript-utils 里是countDown

**Comment by D-xuanmo** [comment]
应该是我之前改了导出方法名，这边没有更新
