### ISSUE TITLE
编译后引入文件报错

### ISSUE THREAD

**Issue by leeggco** [D-xuanmo/v-form#69]
import vform from './lib/vform/VFormDesigner.umd.js'
import './lib/vform/VFormDesigner.css'
Vue.use(vform)  //同时注册了v-form-designer、v-form-render等组件

报错提示：
"export 'default' (imported as 'vform') was not found in './lib/vform/VFormDesigner.umd.js'

**Comment by smilebkf** [comment]
怎么解决的
